apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-service
  labels:
    app: db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: db
    #tier: mysql
  clusterIP: None