apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-map
data:
  mysql-server: demo-app-mysql    # The name of mysql service
  mysql-database-name: demoDb     # The name of the database used by the demo app
  mysql-user-username: myUser
  mysql-database-host: mysql
  DB_URL: jdbc:mysql://mysql/demoDb?useSSL=false