apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: java-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springboot-deployment
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60